dist: bionic  # ubuntu 18.04
language: python

python:
  - "3.6"

cache: pip

install:
  - pip install -r test_requirements.txt
  - python setup.py develop --user

script:
  - python -m flake8 .
  - python -m isort -rc --check-only --diff .
